title: 18F Capacity Planning

theme: uswds-jekyll

styles:
  - /assets/uswds/css/uswds.min.css
  - /assets/css/main.css

scripts:
  - src: /assets/uswds/js/uswds.min.js
    async: true
  - src: /assets/js/main.js
    async: true
